#!/usr/bin/tclsh

# Carve works like 'cut', but allows also to specify end-of-range

set range [lindex $argv 0]

# np.:
# carve 1--2

set parts [split $range -]
set from [expr [lindex $parts 0]-1]

if { [lindex $parts 1] == "" } {
    set to "end-[lindex $parts 2]"
} else {
    set to [expr [lindex $parts 1]-1]
}

while 1 {
    set n [gets stdin line]
    if { $n == -1 } break
    puts [string range $line $from $to]
}
