#!/usr/bin/tclsh

set filename [lindex $argv end]
set options [lrange $argv 0 end-1]

proc runecho args {
	puts ">>> $args"
	exec 2>@stderr >@stdout {*}$args
}

set extmap {
	gz gzip
	bz2 bzip2
	lz lzma
	lzma lzma
	Z compress
	xz xz
}

proc cprog filename {
	set ext [string range [file extension $filename] 1 end]
	
	return [dict get $::extmap $ext]
}

runecho tar "--use-compress-program=[cprog $filename]" -xf {*}$options $filename

